STATE_CHOICES = [
    ('ANP', 'Andhra Pradesh'),
    ('ARP', 'Arunachal Pradesh'),
    ('ASS', 'Assam'),
    ('BIH', 'Bihar'),
    ('CHH', 'Chhattisgarh'),
    ('GOA', 'Goa'),
    ('GUJ', 'Gujarat'),
    ('HAR', 'Haryana'),
    ('HIP', 'Himachal Pradesh'),
    ('JHA', 'Jharkhand'),
    ('KAR', 'Karnataka'),
    ('KER', 'Kerala'),
    ('MAD', 'Madhya Pradesh'),
    ('MAH', 'Maharashtra'),
    ('MAN', 'Manipur'),
    ('MEG', 'Meghalaya'),
    ('MIZ', 'Mizoram'),
    ('NAG', 'Nagaland'),
    ('ODI', 'Odisha'),
    ('PUN', 'Punjab'),
    ('RAJ', 'Rajasthan'),
    ('SIK', 'Sikkim'),
    ('TAM', 'Tamil Nadu'),
    ('TEL', 'Telangana'),
    ('TRI', 'Tripura'),
    ('UTP', 'Uttar Pradesh'),
    ('UTT', 'Uttarakhand'),
    ('WEB', 'West Bengal'),
    ('ANI', 'Andaman and Nicobar Islands'),
    ('CHA', 'Chandigarh'),
    ('DNH', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('LAK', 'Lakshadweep'),
    ('DEL', 'Delhi - National Capital Territory of Delhi'),
    ('PUD', 'Puducherry'),
    ('JAK', 'Jammu and Kashmir'),
    ('LAD', 'Ladakh'),
]
